const post = {
    id: 17665,
    date: '2025-04-19T15:44:52',
    date_gmt: '2025-04-19T20:44:52',
    guid: { rendered: 'https://ccamuseum.org/?p=17665' },
    modified: '2025-04-19T17:19:29',
    modified_gmt: '2025-04-19T22:19:29',
    slug: 'celebrating-20-years-camocs-annual-benefit-dinner',
    status: 'publish',
    type: 'post',
    link: 'https://ccamuseum.org/celebrating-20-years-camocs-annual-benefit-dinner/',
    title: { rendered: 'Celebrating 20 Years: CAMOC’s Annual Benefit Dinner' },
    content: {
      rendered: '<p>On April 5, 2025, the Chinese American Museum of Chicago (CAMOC) hosted its 24th Annual Benefit Dinner, <em>“Celebrating 20 Years Strong, Building 20 Years More,”</em> at New Furama Restaurant. Read featured coverage of the evening from local media outlets!<br></p><hr class="wp-block-separator has-alpha-channel-opacity"/><p>CHICAGO CHINESE NEWS &#8211; Chicago&#8217;s Chinese American Museum 20th Anniversary Celebration was held grandly, with hundreds of overseas Chinese leaders participating in the event to inherit a new chapter in Chinese history </p><div class="wp-block-buttons is-layout-flex wp-block-buttons-is-layout-flex"><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="https://chicagochinesetimes.com/2025/04/06/%e8%8a%9d%e5%8a%a0%e5%93%a5%e8%8f%af%e8%a3%94%e5%8d%9a%e7%89%a9%e9%a4%a820%e5%91%a8%e5%b9%b4%e6%85%b6%e5%85%b8-%e7%9b%9b%e5%a4%a7%e8%88%89%e8%a1%8c-%e7%99%be%e4%bd%8d%e5%83%91%e9%a0%98%e5%85%b1/">Read Here</a></div></div><p><br>CHINA JOURNAL &#8211; Chicago&#8217;s Chinese American Museum celebrates 20th anniversary with annual fundraising gala to honor outstanding community contributors</p><div class="wp-block-buttons is-layout-flex wp-block-buttons-is-layout-flex"><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="https://chinajournal.news/%e8%8a%9d%e5%8a%a0%e5%93%a5%e7%be%8e%e6%b4%b2%e5%8d%8e%e8%a3%94%e5%8d%9a%e7%89%a9%e9%a6%86%e5%ba%86%e7%a5%9d%e6%88%90%e7%ab%8b%e4%ba%8c%e5%8d%81%e5%91%a8%e5%b9%b4%e5%b9%b4%e5%ba%a6%e5%8b%9f%e6%ac%be/">Read Here</a></div></div><p></p><p>SINGTAO &#8211; 300 guests attended the Chinese American Museum of Chicago&#8217;s Fundraising Gala</p><div class="wp-block-buttons is-layout-flex wp-block-buttons-is-layout-flex"><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="https://www.singtaousa.com/2025-04-09/%e8%8f%af%e5%8d%9a%e6%9c%83%e6%85%88%e5%96%84%e7%b1%8c%e6%ac%be%e6%99%9a%e6%9c%83300%e5%98%89%e8%b3%93%e5%87%ba%e5%b8%ad/5198148">Read Here</a></div></div><p><br>UNRULY VISION &#8211; 20 years of glory, inheritance of overseas: The 24th charity dinner of the Chinese American Museum of Chicago was held grandly</p><div class="wp-block-buttons is-layout-flex wp-block-buttons-is-layout-flex"><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="https://mp.weixin.qq.com/s/SwJQtRCed_gD6leT-wBXEg">Read Here</a></div></div><p></p>',
      protected: false
    },
    excerpt: {
      rendered: '<p>On April 5, 2025, the Chinese American Museum of Chicago (CAMOC) hosted its 24th Annual Benefit Dinner, “Celebrating 20 Years&hellip; <a class="read-more" href="https://ccamuseum.org/celebrating-20-years-camocs-annual-benefit-dinner/">Read more <span class="screen-reader-text">Celebrating 20 Years: CAMOC’s Annual Benefit Dinner</span></a></p>\n',
      protected: false
    },
    author: 1,
    featured_media: 0,
    comment_status: 'closed',
    ping_status: 'closed',
    sticky: false,
    template: '',
    format: 'standard',
    meta: {
      _coblocks_attr: '',
      _coblocks_dimensions: '',
      _coblocks_responsive_height: '',
      _coblocks_accordion_ie_support: '',
      _monsterinsights_skip_tracking: false,
      _monsterinsights_sitenote_active: false,
      _monsterinsights_sitenote_note: '',
      _monsterinsights_sitenote_category: 0,
      advanced_seo_description: '',
      jetpack_seo_html_title: '',
      jetpack_seo_noindex: false,
      jetpack_post_was_ever_published: false,
      _jetpack_newsletter_access: '',
      _jetpack_dont_email_post_to_subs: false,
      _jetpack_newsletter_tier_id: 0,
      _jetpack_memberships_contains_paywalled_content: false,
      _jetpack_memberships_contains_paid_content: false,
      footnotes: '',
      jetpack_publicize_message: '',
      jetpack_publicize_feature_enabled: true,
      jetpack_social_post_already_shared: true,
      jetpack_social_options: { image_generator_settings: [Object], version: 2 }
    },
    categories: [ 52698223 ],
    tags: [],
    class_list: [
      'post-17665',
      'post',
      'type-post',
      'status-publish',
      'format-standard',
      'hentry',
      'category-museum-in-the-news'
    ],
    jetpack_publicize_connections: [],
    jetpack_featured_media_url: '',
    jetpack_sharing_enabled: true,
    jetpack_shortlink: 'https://wp.me/p5FB12-4AV',
    jetpack_likes_enabled: false,
    amp_enabled: true,
    _links: {
      self: [ [Object] ],
      collection: [ [Object] ],
      about: [ [Object] ],
      author: [ [Object] ],
      replies: [ [Object] ],
      'version-history': [ [Object] ],
      'predecessor-version': [ [Object] ],
      'wp:attachment': [ [Object] ],
      'wp:term': [ [Object], [Object] ],
      curies: [ [Object] ]
    }
  }