import { hostname } from "os";

export const config = {
	//baseUrl: "https://windpress.wpenginepowered.com/",
	//baseUrl: "https://aerialphotographylouisville.com/",


	//baseUrl: "https://oldhamkyhistory.com/",
	//hostname: "oldhamkyhistory.com",
	
	//baseUrl: "https://slovenianunion.org/",
	//hostname: "slovenianunion.org",

	baseUrl: "https://ccamuseum.org/",
	hostname: "ccamuseum.org",




	meatadata: {
		title: "Oldham County History Center",
		description: "Generated by create next app"
	},
	logo: {
		src: "/ochc.png",
		width: 1330,
		height: 400,
		alt: "History Center Logo"
	}, 
	contact: {
		address: "106 N 2nd St, La Grange, KY 40031",
		email: "info@oldhamkyhistory.com",
		phone: "(502) 222-0826",
		// For Changes to socials, update the following files: 
		// @/components/icons.tsx
		// @/components/social-cluster.tsx
		socials: [
			{ 
				title: "Facebook", 
				link: "https://www.facebook.com/OldhamKYHistory/" 
			},
			{ 
				title: "Instagram", 
				link: "https://www.instagram.com/oldhamkyhistory/" 
			},
			{ 
				title: "Twitter", 
				link: "https://x.com/OldhamKYHistory" 
			},
		],
	},
	footerData: {
		emailSlogan: "Subscribe to our newsletter. Join our newsletter…We won't bombard you with junk email!",
		hours: [
			{ day: "M:", time: "Closed" },
			{ day: "Tu:", time: "Closed" },
			{ day: "W:", time: "10:00 a.m. - 3:00 p.m." },
			{ day: "Th:", time: "10:00 a.m. - 3:00 p.m." },
			{ day: "F:", time: "10:00 a.m. - 3:00 p.m." },
			{ day: "Sa:", time: "10:00 a.m. - 1:00 p.m." },
			{ day: "Su:", time: "Closed" },
		],
		blocks: [
			{
				blockTitle: "History Center:",
				links: [
					{
						title: "Donate",
						link: "#"
					},
					{
						title: "History Center Staff",
						link: "/content/history-center-staff"
					},
					{
						title: "Board of Directors",
						link: "https://oldhamkyhistory.com/wp-content/uploads/2021/10/About-Us-2021-Board-of-Directors.pdf"
					},
					{
						title: "Impact Reports",
						link: "https://oldhamkyhistory.com/wp-content/uploads/2020/11/2020-Impact-Statement.pdf"
					},
					{
						title: "Privacy Policy",
						link: "#"
					},
					{
						title: "Bylaws",
						link: "https://oldhamkyhistory.com/wp-content/uploads/2020/01/2020-Bylaws.pdf"
					},
					{
						title: "Strategic Plan",
						link: "https://oldhamkyhistory.com/wp-content/uploads/2020/01/2019-2020-Strageic-Plan.pdf"
					},
				]
			},
		],
		buttons: {
			button0Link: "/content/donate",
			botton0Text: "Support Us",
			button1Link: "/content/hours-admission",
			button1Text: "Plan Your Visit"
		},
		rightsReserved: "by Oldham County Historical Society. All rights reserved.",
	},
	navMenu: {
		utilityBanner: {
			text: "Plan Your Visit",
			link: "/content/hours-admission"
		},
		staticRoute: {
			title: "Donate",
			link: "/content/donate",
			description: `
				Whether you would like to donate your time or contribute 
				financially to a special project, we at the Oldham County 
				Historical Society are thankful for you!
			`
		},
		linkTree: [
			{
				type: "headlessTree",
				title: "Visit",
				links: [
					{ 
						key: 1, 
						title: 'Hours & Admission', 
						description: 'Plan your trip',
						href: '/content/hours-admission'
					},
					{ 
						key: 2, 
						title: 'Our Campus', 
						description: 'The Oldham County History Center Campus is located just 25 minutes from downtown Louisville',
						href: '/content/our-campus'
					},
					{ 
						key: 3, 
						title: 'Road Warrior Statue', 
						description: 'Heilman’s motorcycle is a special “Marine” issue with the Marine insignia on the side',
						href: '/content/road-warrior-sculpture'
					},
				]
			},
			{
				type: "headlessTree",
				title: "Museum",
				links: [{ 
					key: 1, 
					title: 'Henry Bibb', 
					description: 'Henry Bibb was a prominent abolitionist who endured and overcame slavery to become the first black editor of a newspaper in Canada',
					href: '/content/henry-bibb'
				},
				{ 
					key: 2, 
					title: 'World War II Exhibit', 
					description: 'The Oldham County History Center honors the military service of men and women from the community',
					href: '/content/world-war-ii-exhibit'
				},
				{ 
					key: 3, 
					title: 'Kentucky State Reformatory', 
					description: 'The Kentucky State Reformatory was the third prison built in the Commonwealth of Kentucky following the establishment of a penal system by Kentucky’s Legislature in 1798.',
					href: '/content/ky-state-reformatory'
				},
				{ 
					key: 4, 
					title: 'D.W. Griffith Theater', 
					description: 'Oldham County native filmmaker, D.W. Griffith',
					href: '/content/d-w-griffith-theater'
				},
				{ 
					key: 5, 
					title: 'Order of the Eastern Star', 
					description: 'In 1848, Morris introduced the degrees of the Order of the Eastern Star as a part of the freemasonry fraternal organizations',
					href: '/content/eastern-star'
				},
				{ 
					key: 6, 
					title: 'Little Colonel', 
					description: 'Annie Fellows Johnston (author of the “Little Colonel” novels)',
					href: '/content/little-colonel'
				},
				{ 
					key: 7, 
					title: 'Other Exhibits', 
					description: 'The Oldham County Historical Society has compiled an extensive collection of exhibits that are sure to pique your interest',
					href: '/content/other-exhibits'
				},]
			},
			{
				type: "headlessTree",
				title: "Underground Railroad",
				links: [
					{ 
						key: 1, 
						title: 'Nationalal Park Service Designation', 
						description: 'July 2016 the Oldham County Historical Society was included in the National Park Service National Underground Railroad Network to Freedom',
						href: '/content/national-park-service'
					},
					{ 
						key: 2, 
						title: 'Oldham KY Archives', 
						description: 'The J. C. Barnett Library and Archives on the Oldham County History Center campus was built in 1840 and served as the home of Amanda and James Mount.',
						href: '/content/archives'
					},
					{ 
						key: 3, 
						title: 'Henry Bibb', 
						description: 'Henry Bibb was a prominent abolitionist who endured and overcame slavery to become the first black editor of a newspaper in Canada.',
						href: '/content/henry-bibb'
					},
					{ 
						key: 4, 
						title: 'Amos Mount Civil War Letters', 
						description: 'Lucretia Davenport donated a collection of artifacts to the Oldham County History Center that belonged to her late husband, John McRoberts Mount',
						href: '/content/civil-war-letters'
					},
					{ 
						key: 5, 
						title: 'Thirty Days of Stories on the Underground Railroad in Kentucky',
						description: 'A Podcast Series presented by The Oldham County History Center on the Oldham Podcast Network', 
						href: '/content/underground-railroad-podcast'
					},
				]
			},
			{
				type: "headlessTree",
				title: "Research",
				links: [
					{ 
						key: 1, 
						title: 'Library & Archives', 
						description: 'The J. C. Barnett Library and Archives is located in the James and Amanda Mount House',
						href: '/content/library-and-archives'
					},
					{ 
						key: 2, 
						title: 'Cemeteries & Graves', 
						description: 'We have many visitors from all over the United States and different countries that visit our Cemeteries and Archives to research their ancestors',
						href: '/content/cemeteries-and-graves'
					},
					{ 
						key: 3, 
						title: 'African American Geneology', 
						description: 'Oldham County had many people who resisted slavery and there are many throughout the state of Kentucky but often their stories were buried with their attempt of escape or resistance',
						href: '/content/african-american-geneology'
					},
					{ 
						key: 4, 
						title: '1879 Oldham Jefferson Atlas', 
						description: 'This atlas contains exquisite detail of individual property holdings, roads, towns, etc.',
						href: '/content/1879-atlas'
					},
					{ 
						key: 5, 
						title: 'Famous People of Oldham', 
						description: 'Oldham County has been pivotal to the formation of American history',
						href: '/content/famous-people'
					},
					{ 
						key: 6, 
						title: 'Historic Sites of Oldham', 
						description: 'Oldham is chock full of fascinating historic sites with some that have been tucked behind more progressive ones',
						href: '/content/historic-sites-of-oldham'
					},
				]
			},
			{
				type: "headlessTree",
				title: "Projects",
				links: [
					{ 
						key: 1, 
						title: 'Oldhams Veterans Oral Histories', 
						description: 'Oldham is chock full of fascinating historic sites with some that have been tucked behind more progressive ones',
						href: '/content/veterans-oral-histories'
					},
					{ 
						key: 2, 
						title: 'Earl D. Bennett WWII Letters', 
						description: 'Earl’s squadron assisted with the Normandy landings during and after D-Day on June 6th, 1944ss',
						href: '/content/earl-d-bennett-wwii-letters'
					},
					{ 
						key: 3, 
						title: 'Living Treasures of Oldham', 
						description: 'In 2007 The Oldham Era and Oldham County History Center launched The Living Treasures Program that publicly recognizes people who have generously served our community with kind hearts and good deeds',
						href: '/content/living-treasures'
					},
					{ 
						key: 4, 
						title: 'History Markers', 
						description: 'Since 1949, the Kentucky Historical Marker program has allowed communities across Kentucky to recognize and share the sites',
						href: '/content/history-markers'
					},
					{ 
						key: 5, 
						title: 'Campus Renovations', 
						description: 'Campaign Update 2020 Over $2 Million Raised!',
						href: '/content/campus-renovations'
					},
				]
			},
			{
				type: "headlessTree",
				title: "Events",
				links: [
					{ 
						key: 1, 
						title: 'Calendar', 
						description: 'Find our events to attend',
						href: '/events'
					},
					{ 
						key: 2, 
						title: 'Annual Events', 
						description: 'Here is a list of our popular tried-and-true events that you can expect each year',
						href: '/content/annual-events'
					},
					{ 
						key: 3, 
						title: 'Special Events', 
						description: 'Our special events include Appraisal Fairs, Candlelight Cemetery Tours & Rob Morris Historic Home Tour Series',
						href: '/content/special-events'
					},
				]
			},
			{
				type: "singleNode",
				title: "Donate",
				link: "/content/donate"
			},
		]
	},
	wp: {
		thumbnailFallback: '/Hermitage-600x400.jpg',
		fallbackVenue: "Oldham Co History Center Campus"
	},
}





